=== slodkadziewczyna33/PaczkownicyInfaPG/paczka/SEM1/HiH_Hipertekst_i_Hipermedia/laboratoria/wspólne/lab_02/hih_lab_02_rozwiązania/HH.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
<!--Piotr Trybisz-->
	<!--element 'hipertext' jest zadeklarowany globalnie. W pliku XML jest elementem głównym - korzeniem-->
	<xs:element name="hipertext" type="hipertextType"/>  

	<!-- typ hipertextType jest zdefiniowany globalnie i użyty w deklaracji elementu hipertext-->
	<xs:complexType name="hipertextType">
		<xs:sequence>
			<xs:element name="author" type="authorType" /> 	<!--lokalna deklaracja elementu author. Typ dla tego elementu został zdefiniowany globalnie-->
			<xs:element name="definition" type="definitionType">   <!--lokalna deklaracja elementu definition-->
				
			</xs:element>
			<xs:element type="personsType" name="persons"></xs:element>
			<xs:element name="systems" type="systemsType" minOccurs="0"/>	<!--lokalna deklaracja elementu systems, który jest typu złożonego zdefiniowanego globalnie-->
		</xs:sequence>
	</xs:complexType>

	<!-- typ authorType jest typem złożonym zdefiniowanym globalnie i został użyty w deklaracji elementu author -->
	<xs:complexType name="authorType">
		<xs:sequence>
			<xs:element name="name" type="shortStringType" />		<!--lokalna deklaracja elementu name, który jest typu wbudowanego string-->
			<xs:element name="surname" type="shortStringType" />	<!--lokalna deklaracja elementu surname, który jest typu wbudowanego string-->
		</xs:sequence>
	</xs:complexType>

	<!-- typ systemsType jest typem złożonym zdefiniowanym globalnie i został użyty w deklaracji elementu systems -->
	<xs:complexType name="systemsType">
		<xs:sequence>
			<xs:element name="system" minOccurs="0" maxOccurs="unbounded">	<!--element system jest zadeklarowany lokalnie. Typ dla tego elementu również został zdefiniowany lokalnie-->
				<xs:complexType>		<!--lokalna definicja typu złożonego dla elementu system -->
					<xs:sequence>
						<xs:element name="name" type="xs:string" />			<!--lokalna deklaracja elementu name, który jest typu wbudowanego string-->
						<xs:element name="description" type="xs:string" />
						<!--lokalna deklaracja elementu description, który jest typu wbudowanego string-->
						<xs:element ref="image" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="adressType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="source" type="xs:anyURI" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:simpleType name="shortStringType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="30"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="longStringType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="70"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="image" type="adressType" />
	<xs:element name="link" type="adressType" />
	
	<xs:complexType name="personsType">
		<xs:sequence>
			<xs:element name="person" maxOccurs="unbounded" type="personType"></xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="personType">
		<xs:complexContent>
			<xs:extension base="authorType">
				<xs:sequence>
			<xs:element name="birth" type="xs:gYear"></xs:element>
			<xs:element name="death" minOccurs="0" type="xs:gYear"></xs:element>
			<xs:element name="about" type="xs:string"></xs:element>
			<xs:element ref="image"></xs:element>
			<xs:element ref="link"></xs:element>
			<xs:element name="achievements">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="achievement" type="achievementType" maxOccurs="unbounded">
							
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="alive" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="yes"></xs:enumeration>
					<xs:enumeration value="no"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="achievementType">
		<xs:sequence>
			<xs:element name="title" type="longStringType"></xs:element>
			<xs:element name="description" type="xs:string"></xs:element>
			<xs:element ref="image" minOccurs="0"></xs:element>
			<xs:element ref="link" minOccurs="0"></xs:element>
		</xs:sequence>
		<xs:attribute name="n" type="xs:int"></xs:attribute>
	</xs:complexType>
	
	<xs:simpleType name="definitionType">
		<xs:restriction base="xs:string">
			<xs:minLength value="15"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>




<!--
deklaracja elementu globalnego
<xs:element name="elemName" type="elemType" />

deklaracja elementu poprzez referencję
<xs:element ref="elemName" minOccurs="0" maxOccurs="unbounded"/>
-->

=== slodkadziewczyna33/PaczkownicyInfaPG/paczka/SEM1/HiH_Hipertekst_i_Hipermedia/laboratoria/wspólne/lab_02/hih_lab_02_rozwiązania/HH.xml
<?xml version="1.0" encoding="utf-8"?>
<hipertext xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="HH.xsd">
	<author>
		<name>Piotr</name>
		<surname>Trybisz</surname>
	</author>
	<definition>
		Hipertext is a nonlinear text material.
	</definition>
	<systems>
		<system>
			<name>HyperCard</name>
			<description>
				HyperCard was a powerful, yet extremely easy to use tool for creating “stacks” — essentially flat-file databases that used hyperlinks as a way of navigating a stack of “cards”.
			</description>
		</system>
		<system>
			<name>World Wide Web</name>
			<description>
				The World Wide Web is a collection of linked resources and documents, connected by hyperlinks and URLs
			</description>
		</system>
	</systems>
</hipertext>

=== slodkadziewczyna33/PaczkownicyInfaPG/paczka/SEM1/(HiH)_Hipertekst_i_Hipermedia/laboratoria/wspólne/lab_02/hih_lab_02_rozwiązania/HH_15.xml
<?xml version="1.0" encoding="utf-8"?>
<hipertext xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="HH.xsd">
	<author>
		<name>Piotr</name>
		<surname>Trybisz</surname>
	</author>
	<definition>
		Hipertext is a nonlinear text material.
	</definition>
	<persons>
		<person alive="no">
			<name>Vannevar</name>
			<surname>Bush</surname>
			<birth>1890</birth>
			<death>1974</death>
			<about>
				Vannevar Bush was a famous scientist in his days and was the science advisor to President Roosevelt during the Second World War, when science-based issues like inventing nuclear weapons were of great importance. After "As We May Think" ran in the Atlantic Monthly , it caused considerable discussion, and both Time and Life ran stories on the  Memex. Life even had an artist draw up illustrations of how the Memex would look and a scenario of its projection positions as the user was completing a link. Doug Engelbart,  who later became a pioneer in the development of interactive computing and invented the mouse, got part of his inspiration by reading Bush's article while waiting for a ship home from the Philippines in 1945. In spite of all this early interest surrounding the Memex it never got built. As hinted above, our current computer technology is still not able to support Bush's vision in its entirety. We do have computers with most of the Memex functionality but they are based on a completely different technology from the microfilm discussed by Bush.
			</about>
			<image source="img/Vannevar-Bush.jpg">Vannevar Bush</image>
			<link source="https://www.britannica.com/topic/Harvard-University">Vannevar Bush</link>
			<achievements>
				<achievement n="1">
					<title>Memex - "memory extender"</title>
					<description>
						Bush described the Memex as "a sort of mechanized private file and library" and as "a device in which an individual stores his books, records, and communications, and which is mechanized so that it may be consulted with exceeding speed and flexibility." The Memex would store this information on microfilm, which would be kept in the user's desk. This desk was intended to have several microfilm projection positions to enable the user to compare different microfilms, in a manner very similar to the windows that became popular on personal computers more than forty years later. The Memex would have a scanner to enable the user to input new material, and it would also allow the user to make handwritten marginal notes and comments. But Bush envisaged that most of the Memex contents are purchased on microfilm ready for insertion. Books of all sorts, pictures, current periodicals, newspapers, are thus obtained and dropped into place. Business correspondence takes the same path. Actually we have not yet reached the state of hypertext development where there is a significant amount of preprocessed information for sale that can be integrated with a user's existing hypertext structure.
					</description>
					<image source="img/Memex.jpg">Project of Memex</image>
				</achievement>
			</achievements>
		</person>
		<person alive="yes">
			<name>Tim</name>
			<surname>Berners-Lee</surname>
			<birth>1955</birth>
			<about>
				Sir Tim Berners Lee is an English computer scientist best known as the inventor of the World Wide Web. He is a Professorial Fellow of Computer Science at the University of Oxford and a professor at the Massachusetts Institute of Technology (MIT). Tim Berners-Lee proposed an information management system then implemented the first successful communication between a Hypertext Transfer Protocol (HTTP) client and server via the Internet.
			</about>
			<image source="img/Tim.jpg">Sir Tim Berners-Lee</image>
			<link source="https://www.britannica.com/biography/Tim-Berners-Lee">Sir Tim Berners-Lee</link>
			<achievements>
				<achievement n="1">
					<title>HTML</title>
					<description>
						Hypertext Markup Language - The markup (formatting) language for the web.
					</description>
					<link source="https://www.w3schools.com/html/">HTML w3schools</link>
				</achievement>
				<achievement n="2">
					<title>URI</title>
					<description>
						Uniform Resource Identifier. A kind of "address" that is unique and used to identify to each resource on the web.
					</description>
				</achievement>
				<achievement n="3">
					<title>HTTP</title>
					<description>
						Hypertext Transfer Protocol. Allows for the retrieval of linked resources from across the web.
					</description>
				</achievement>
				<achievement n="4">
					<title>Browser</title>
					<description>
						A computer program with a graphical user interface for displaying and navigating between web pages.
					</description>
					<image source="img/browser.jpg">The first web page</image>
				</achievement>
			</achievements>
		</person>
	</persons>
	<systems>
		<system>
			<name>HyperCard</name>
			<description>
				HyperCard was a powerful, yet extremely easy to use tool for creating “stacks” — essentially flat-file databases that used hyperlinks as a way of navigating a stack of “cards”.
			</description>
			<image source="hypercard.jpg">HyperCard system</image>
			<link source="https://hypercard.org/">HyperCard</link>
			<link source="https://www.youtube.com/watch?v=2K1C5BZKP3I">Why HyperCard was so f***ing Great!</link>
			<link source="https://eshop.macsales.com/blog/64930-hypercard-one-stack-at-a-time/">HyperCard</link>
		</system>
		<system>
			<name>World Wide Web</name>
			<description>
				The World Wide Web is a collection of linked resources and documents, connected by hyperlinks and URLs
			</description>
			<link source="https://www.w3schools.com/html/">HTML w3schools</link>
		</system>
	</systems>
</hipertext>

=== slodkadziewczyna33/PaczkownicyInfaPG/paczka/SEM1/(HiH)_Hipertekst_i_Hipermedia/laboratoria/wspólne/lab_02/hih_lab_02_rozwiązania/HH_13.xml
<?xml version="1.0" encoding="utf-8"?>
<hipertext xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="HH.xsd">
	<author>
		<name>student's name</name>
		<surname>student's surname </surname>
	</author>
	<definition>
		Hipertext is a nonlinear text material.
	</definition>
	<persons>
		<person alive="no">
			<name>Vannevar</name>
			<surname>Bush</surname>
			<birth>1890</birth>
			<death>1974</death>
			<about>
				Vannevar Bush was a famous scientist in his days and was the science advisor to President Roosevelt during the Second World War, when science-based issues like inventing nuclear weapons were of great importance. After "As We May Think" ran in the Atlantic Monthly , it caused considerable discussion, and both Time and Life ran stories on the  Memex. Life even had an artist draw up illustrations of how the Memex would look and a scenario of its projection positions as the user was completing a link. Doug Engelbart,  who later became a pioneer in the development of interactive computing and invented the mouse, got part of his inspiration by reading Bush's article while waiting for a ship home from the Philippines in 1945. In spite of all this early interest surrounding the Memex it never got built. As hinted above, our current computer technology is still not able to support Bush's vision in its entirety. We do have computers with most of the Memex functionality but they are based on a completely different technology from the microfilm discussed by Bush.
			</about>
			<image source="img/Vannevar-Bush.jpg">Vannevar Bush</image>
			<link source="https://www.britannica.com/topic/Harvard-University">Vannevar Bush</link>
		</person>
		<person alive="yes">
			<name>Tim</name>
			<surname>Berners-Lee</surname>
			<birth>1955</birth>
			<about>
				Sir Tim Berners Lee is an English computer scientist best known as the inventor of the World Wide Web. He is a Professorial Fellow of Computer Science at the University of Oxford and a professor at the Massachusetts Institute of Technology (MIT). Tim Berners-Lee proposed an information management system then implemented the first successful communication between a Hypertext Transfer Protocol (HTTP) client and server via the Internet.
			</about>
			<image source="img/Tim.jpg">Sir Tim Berners-Lee</image>
			<link source="https://www.britannica.com/biography/Tim-Berners-Lee">Sir Tim Berners-Lee</link>
		</person>
	</persons>
	<systems>
		<system>
			<name>HyperCard</name>
			<description>
				HyperCard was a powerful, yet extremely easy to use tool for creating “stacks” — essentially flat-file databases that used hyperlinks as a way of navigating a stack of “cards”.
			</description>
			<image source="hypercard.jpg">HyperCard system</image>
			<link source="https://hypercard.org/">HyperCard</link>
			<link source="https://www.youtube.com/watch?v=2K1C5BZKP3I">Why HyperCard was so f***ing Great!</link>
			<link source="https://eshop.macsales.com/blog/64930-hypercard-one-stack-at-a-time/">HyperCard</link>
		</system>
		<system>
			<name>World Wide Web</name>
			<description>
				The World Wide Web is a collection of linked resources and documents, connected by hyperlinks and URLs
			</description>
			<link source="https://www.w3schools.com/html/">HTML w3schools</link>
		</system>
	</systems>
</hipertext>

=== slodkadziewczyna33/PaczkownicyInfaPG/paczka/SEM1/(HiH)_Hipertekst_i_Hipermedia/laboratoria/wspólne/lab_02/hih_lab_02_rozwiązania/HH_10.xml
<?xml version="1.0" encoding="utf-8"?>
<hipertext xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="HH.xsd">
	<author>
		<name>student's name</name>
		<surname>student's surname </surname>
	</author>
	<definition>
		Hipertext is a nonlinear text material.
	</definition>
	<systems>
		<system>
			<name>HyperCard</name>
			<description>
				HyperCard was a powerful, yet extremely easy to use tool for creating “stacks” — essentially flat-file databases that used hyperlinks as a way of navigating a stack of “cards”.
			</description>
			<image source="hypercard.jpg">HyperCard system</image>
			<link source="https://hypercard.org/">HyperCard</link>
			<link source="https://www.youtube.com/watch?v=2K1C5BZKP3I">Why HyperCard was so f***ing Great!</link>
			<link source="https://eshop.macsales.com/blog/64930-hypercard-one-stack-at-a-time/">HyperCard</link>
		</system>
		<system>
			<name>World Wide Web</name>
			<description>
				The World Wide Web is a collection of linked resources and documents, connected by hyperlinks and URLs
			</description>
			<link source="https://www.w3schools.com/html/">HTML w3schools</link>
		</system>
	</systems>
</hipertext>
